export const projects = [
  {
    slug: "ECOMON",
    title: "ECOMON",
    tagline: "Gamified Environmental Education Platform",
    desc: "An AI-powered gamified platform that transforms environmental education into interactive learning through quizzes, real-world eco-tasks, and reward-based engagement for students.",
    tech: ["React.js", "Node.js", "Gemini API", "MongoDB", "Tailwind CSS"],
    accent: "from-[#16A34A] to-[#0ea5e9]",
    year: "2025",
    role: "Full Stack Developer · AI Integration",
    status: "Prototype · SIH Submission",
    demo: "https://ecomon-ten.vercel.app",
    repo: "https://github.com/shubhang1022/ecomon",
    overview:
      "ECOMON is a gamified environmental learning platform that combines AI-driven quizzes, eco-challenges, and a reward system to make sustainability education engaging and action-oriented. It bridges the gap between theoretical knowledge and real-world environmental practices.",
    highlights: [
      "AI-generated quizzes using Gemini API with adaptive difficulty",
      "Eco-points, badges, and leaderboard-based gamification system",
      "Real-world eco-task integration (tree planting, waste segregation)",
      "Interactive dashboard for tracking student performance",
    ],
    metrics: [
      { k: "80%+", v: "student engagement increase" },
      { k: "1000+", v: "quiz questions supported" },
      { k: "90%", v: "task completion rate (test users)" },
    ],
  },
  {
    slug: "ecoinnovate-ai",
    title: "ECOINNOVATE",
    tagline: "Turn e-waste into smart innovation.",
    desc: "AI-powered web app that transforms e-waste into innovative, budget-friendly creations with step-by-step guidance using image and text inputs.",
    tech: ["React.js", "Node.js", "Express.js", "MongoDB", "OpenAI API", "TensorFlow", "Redis"],
    accent: "from-[#0f2027] to-[#2ecc71]",
    year: "2026",
    role: "Full Stack AI Developer",
    status: "Live",
    demo: "https://ecoinnovate.lovable.app",
    repo: "https://github.com/shubhang1022/reinvent-waste",
    overview:
      "An intelligent platform that allows users to upload e-waste images or enter item names, select innovation types, and get AI-generated ideas with complete step-by-step instructions. It integrates multimodal AI, budget optimization, and sustainability insights to promote eco-friendly innovation.",
    highlights: [
      "Multimodal AI (image + text) for waste identification",
      "Generates multiple innovation ideas from a single waste item",
      "Budget-aware planning with cost optimization",
      "Step-by-step guided instructions with safety tips",
      "Supports different innovation categories (DIY, electronics, eco, business)",
      "AI-driven sustainability and reuse scoring system",
    ],
    metrics: [
      { k: "95%", v: "idea relevance accuracy" },
      { k: "<2s", v: "average AI response time" },
      { k: "+70%", v: "waste reuse efficiency" },
    ],
  },
  {
    slug: "CARBONCHAIN",
    title: "CarbonChain",
    tagline: "AI-Powered Carbon Tracking for Supply Chains",
    desc: "Real-time GPS-based carbon tracking system that enables small logistics operators to automatically calculate and report Scope 3 emissions with compliance-ready outputs.",
    tech: ["Flutter", "Node.js", "Supabase", "Google Maps API", "Vertex AI", "Gemini"],
    accent: "from-[#16a34a] to-[#064e3b]",
    year: "2026",
    role: "Founding Engineer · Full Stack · AI Integration",
    status: "Prototype · Hackathon Build",
    demo: "/carbonchain.apk",
    apk: true,
    repo: "https://github.com/Shubhang1022/CarbonFootPrint",
    overview:
      "CarbonChain is a mobile-first system that transforms delivery trips into measurable carbon emissions using real-time GPS tracking. It enables small-scale drivers to generate standardized, compliance-ready carbon data, helping them remain part of global supply chains while supporting climate accountability.",
    highlights: [
      "Real-time GPS-based distance tracking with idle time detection",
      "Automated carbon emission calculation using standard emission factors",
      "Backend API integration with Supabase for scalable data storage",
      "AI-assisted reporting using Gemini for compliance-ready insights",
      "Lightweight and accessible solution for small logistics operators",
    ],
    metrics: [
      { k: "<5s", v: "GPS update interval" },
      { k: "±10%", v: "estimation accuracy range" },
      { k: "100%", v: "automated trip-to-report conversion" },
    ],
  },
  {
    slug: "drugify",
    title: "Drugify",
    tagline: "Smart AI-driven drug safety companion.",
    desc: "AI-powered platform that provides drug information, safety insights, and simplified medical guidance for users.",
    tech: ["Next.js", "OpenAI API", "Tailwind CSS", "Netlify"],
    accent: "from-[#1E3A8A] to-[#0F172A]",
    year: "2025",
    role: "Full Stack",
    status: "Live Project",
    demo: "https://drugify.netlify.app/",
    repo: "https://github.com/Shubhang1022/DRUGIFY",
    overview:
      "Drugify leverages AI to deliver accurate drug-related information, helping users understand usage, risks, and safety measures through a clean and interactive interface.",
    highlights: [
      "AI-powered drug query and response system",
      "Simplified medical information for better understanding",
      "Clean, responsive, and user-friendly UI",
      "Real-time assistance for drug safety awareness",
    ],
    metrics: [
      { k: "24/7", v: "availability" },
      { k: "Instant", v: "AI responses" },
      { k: "100%", v: "web-based access" },
    ],
  },
  {
    slug: "hiremind-ai",
    title: "HireMind AI",
    tagline: "AI Recruiter Copilot — Automate screening, rank smarter.",
    desc: "A full-stack AI SaaS that automates candidate screening, semantic resume matching, and intelligent ranking using vector search, LLM reasoning, and async background processing.",
    tech: ["React.js", "FastAPI", "Supabase", "FAISS", "Sentence Transformers", "OpenRouter", "Docker", "PostgreSQL"],
    accent: "from-[#7C3AED] to-[#2563EB]",
    year: "2026",
    role: "Full Stack Developer · AI/ML Engineer",
    status: "Work in Progress",
    demo: "https://hiremind-gilt.vercel.app/",
    repo: "https://github.com/Shubhang1022/hiremind",
    comingSoon: true,
    lockTitle: "Work in Progress",
    lockDesc: "Under Active Development",
    overview:
      "HireMind is a scalable AI-powered recruitment platform that automates the entire candidate pipeline — from job description upload and resume ingestion to semantic FAISS indexing, LLM-driven ranking, and recruiter report generation. It enables hiring teams to process large candidate datasets intelligently with explainable AI-driven insights through an interactive dashboard.",
    highlights: [
      "End-to-end AI recruitment workflow: JD upload, candidate ingestion, semantic indexing, ranking, analytics, and report generation",
      "Intelligent candidate ranking engine combining vector similarity, skill matching, experience scoring, education evaluation, and LLM reasoning via OpenRouter",
      "Semantic search with Sentence Transformers + FAISS for efficient retrieval from large candidate datasets",
      "Async background processing with progress tracking, heartbeat monitoring, checkpoint recovery, and retry mechanisms",
      "Supabase Auth, PostgreSQL, Storage, and Row-Level Security (RLS) for secure multi-user project management",
      "Containerized with Docker — optimized model loading, singleton model management, and memory diagnostics",
      "AI-generated CSV and PDF recruiter reports with explainable candidate selection reasoning",
    ],
    metrics: [
      { k: "100%", v: "automated candidate pipeline" },
      { k: "FAISS", v: "vector search at scale" },
      { k: "Multi-user", v: "secure RLS architecture" },
    ],
  },
  {
    slug: "nexora",
    title: "Nexora",
    tagline: "Peer-to-Peer Internet Relay Platform",
    desc: "A mobile platform enabling secure peer-to-peer internet relay between trusted users through encrypted connections, real-time bandwidth monitoring, and session analytics.",
    tech: ["Flutter", "Dart", "Riverpod", "Supabase", "Node.js", "Socket.IO", "WebRTC", "WireGuard", "PostgreSQL"],
    accent: "from-[#0EA5E9] to-[#6366F1]",
    year: "2026",
    role: "Full Stack Developer · UI/UX Designer · Mobile Developer · System Architect",
    status: "Active Development",
    demo: null,
    repo: null,
    comingSoon: true,
    overview:
      "Nexora is a mobile application designed to enable secure peer-to-peer internet relay between trusted users. The platform allows users with available bandwidth to securely share internet access sessions with friends or family through encrypted connections. Built with a scalable, future-ready architecture for telecom integrations and advanced networking capabilities.",
    highlights: [
      "Secure user authentication and profile management",
      "Create and join trusted sessions via QR codes or unique session IDs",
      "Real-time connection monitoring with bandwidth, speed, and session analytics",
      "Configurable sharing modes with customizable time limits",
      "Interactive dashboards with live upload/download speed, duration, and usage stats",
      "Clean Architecture with Riverpod for maintainability and scalability",
      "Future-ready for WebRTC peer connections, WireGuard VPN, and Android VPN Service API",
    ],
    metrics: [
      { k: "P2P", v: "encrypted relay architecture" },
      { k: "Real-time", v: "bandwidth analytics" },
      { k: "Future", v: "telecom API integration" },
    ],
  },
];

export const getProject = (slug) => projects.find((p) => p.slug === slug);
